Game logic
karthi07/tic-tac-toe pull request #4
Opened 2020-04-24 11:44 UTC by karthi07

Tic Tac Toe project Milestone 3

 - Create the game winning logic and game tie logic
 - added new file for game board class 
 - print and get input is only at main.rb file

2020-04-27 15:31 UTC, suretrust requested changes
Hi team, 👋 

### Great job thus far! 🙌 Please see my comments. 👇 
* [ ] The project uses at least two classes (Usually it uses three: Game, Board and Player). The code of the project should be logically divided between classes. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/classes.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
* [ ] All classes should be kept in `lib` directory. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

**Kindly submit for another code review request once these issues have been fixed.** _Happy coding!_ 🎉

2020-04-27 18:15 UTC, pelzolga123 requested changes
The project requires changes.

2020-04-27 18:15 UTC, pelzolga123 commented
## Hi Team! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### Your project looks good :+1: 
But still, there are more changes required, before this Pull Request can be approved:
* [ ] The game allows users to live the name blank. It would be great if you could add some validation to prevent it.
* [ ] The code should respect the single responsibility rule for methods (i.e. each method does exactly one thing). Your `game_play` is a long method that is doing multiple steps of the game process. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/single_responsibility.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
* [ ] The game is behaving weirdly after the player entered invalid move and correct one after that:
![image](https://user-images.githubusercontent.com/20416431/80405816-cbf82f80-88cb-11ea-8093-11cc93a8f344.png)

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-04-28 12:08 UTC, mcrd25 approved these changes
# Changes Approved 👍 💪 🎉  ㊗️ 

Hey @karthi07! Hey @suretrust! 👋 

Great job with changes!
No need for further review on my end! 😄 

***If you have any questions, now or in the future, do not hesitate to contact me on social media, email or on slack and I will be glad to chat with you.***

*Happy coding 😄,*
**[--Maya Douglas](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

2020-04-28 12:08 UTC, mcrd25 commented on bin/main.rb
> +  def game_play() # rubocop:disable Metrics/MethodLength
[OPTIONAL]
As mentioned before, your method should follow the single responsibility rule. 
I congratulate you on your attempt so far! 👏 
There are still however some components of its method that you can improve. For instance lines, 79 to 82 could be a method called set players etc.

2020-04-28 13:33 UTC, merged